[package]
name = "simplepaint"
version = "0.1.0"
edition = "2024"


[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
cast_possible_truncation = "allow"
cast_precision_loss = "allow"

[dependencies]
bytemuck = "1.25.2"
egui = "0.36.2"
egui-wgpu = { version = "0.36.2", features = ["winit"] }
egui-winit = "0.36.2"
pollster = "1.0.1"
wgpu = "30.0.1"
winit = "0.30.13"
